name: generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install mustache
        run: sudo apt-get install ruby-mustache

      - name: Install pandoc
        run: sudo apt-get install pandoc
        
      - name: Generate new statute version
        run: make clean && make

      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'gh-pages'
          commit_message: 'update generated files'
