name: generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - uses: ruby/setup-ruby@v1.68.0
#        with:
#          bundler-cache: true


      - name: Install mustache
        run: sudo apt-get install ruby-mustache

      - name: Install pandoc
        run: sudo apt-get install pandoc
        
      - name: Generate new statute version
        run: make
